### PR TITLE
chore: release v0.4.1

### PR DESCRIPTION
**Pull request by vcastellm**
Release v0.4.1

### CODE REVIEW

**Review by ToniRamirezM — APPROVED** [review]

**Review by rachit77 — APPROVED** [review]

**Review by joanestebanr — CHANGES_REQUESTED** [review]
Why the PR is not passing Unit test?

**Comment by vcastellm** [comment]
> Why the PR is not passing Unit test?

It's explained in the slack message

**Comment by joanestebanr** [comment]
> > Why the PR is not passing Unit test?
> 
> It's explained in the slack message: upgrades in Kurtosis that broke the testing

Just for clarify: the unittest are not using Kurtosis, so the problem is another.

**Review by joanestebanr — APPROVED** [review]
I suggest to fix unittest before merging

**Pull request merged**
