### PR TITLE
chore: bump kurtosis-cdk version to support pre-deployed gas token

### PR DESCRIPTION
**Pull request by leovct**
## Description

Related to https://github.com/0xPolygon/kurtosis-cdk/pull/386

It looks like the CI doesn't run the e2e tests on my PR, maybe because it comes from an external fork? I've created a [local PR](https://github.com/leovct/cdk/pull/1) on my fork to make sure they all pass. Note that the fork12-pp test doesn't pass on the `develop` branch either.

Screenshot 2024-11-27 at 10 48 44

### CODE REVIEW

**Review by Stefan-Ethernal — APPROVED** [review]

**Comment by Stefan-Ethernal** [comment]
@leovct the PP E2E tests were fixed through https://github.com/0xPolygon/cdk/pull/198, although it has not landed to the `develop` branch yet.

**Review by vcastellm — APPROVED** [review]
Nice!

**Comment by leovct** [comment]
I'm afraid the SonarCloud job won't pass because I'm opening a PR from an external fork. Is this a blocker for the PR to be merged?

**Comment by Stefan-Ethernal** [comment]
> I'm afraid the SonarCloud job won't pass because I'm opening a PR from an external fork. Is this a blocker for the PR to be merged?

Nope, it is a known issue and you have not affected the source code, therefore it could not have negatively impacted the SonarCloud.

**Pull request merged**
